name: Build & Upload to App Store

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build_and_submit:
    name: Build i Wyślij do App Store
    runs-on: macos-latest

    env:
      APP_SCHEME: "LayerMapper"
      APP_PROJECT: "LayerMapper.xcodeproj"
      APP_EXPORT_METHOD: "app-store"
      APP_BUNDLE_ID: "com.layermapper.mobile"
      APP_ARCHIVE_PATH: "$HOME/Library/Developer/Xcode/Archives/$(date +%Y-%m-%d)/LayerMapper.xcarchive"
      APP_IPA_PATH: "$HOME/LayerMapper.ipa"

    steps:
      # 1) Checkout z LFS
      - name: Check out repository z LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      # 2) Zainstaluj Ruby (aby działalo altool)
      - name: Ustaw Ruby (dla altool)
        run: |
          sudo gem install cocoapods --no-document

      # 3) Stwórz keychain i zaimportuj certyfikat (.p12)
      - name: Create keychain
        run: |
          security create-keychain -p "" build.keychain
          security set-keychain-settings -lut 21600 build.keychain
          security unlock-keychain -p "" build.keychain
          security list-keychains -d user | tr -d '"' | tr '\n' ' ' | \
            xargs security list-keychains -s build.keychain

      # 4) Odszyfruj i zainstaluj Distribution Certificate (.p12)
      - name: Decode and install Distribution Certificate (.p12)
        env:
          P12_BASE64: ${{ secrets.P12_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          echo "$P12_BASE64" | base64 --decode > distribution.p12
          security import distribution.p12 \
            -k ~/Library/Keychains/build.keychain \
            -P "$P12_PASSWORD" \
            -T /usr/bin/codesign

      # 5) Odszyfruj i zainstaluj 3 provisioning profiles
      - name: Decode and install Provisioning Profiles
        env:
          MOBILEPROVISION_BASE64:          ${{ secrets.MOBILEPROVISION_BASE64 }}
          MOBILEPROVISION_BROADCAST_BASE64: ${{ secrets.MOBILEPROVISION_BROADCAST_BASE64 }}
          MOBILEPROVISION_SETUP_BASE64:     ${{ secrets.MOBILEPROVISION_SETUP_BASE64 }}
        run: |
          echo "$MOBILEPROVISION_BASE64" | base64 --decode > LayerMapper.mobileprovision
          echo "$MOBILEPROVISION_BROADCAST_BASE64" | base64 --decode > ScreenBroadcast.mobileprovision
          echo "$MOBILEPROVISION_SETUP_BASE64" | base64 --decode > ScreenBroadcastSetupUI.mobileprovision

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp LayerMapper.mobileprovision            ~/Library/MobileDevice/Provisioning\ Profiles/
          cp ScreenBroadcast.mobileprovision         ~/Library/MobileDevice/Provisioning\ Profiles/
          cp ScreenBroadcastSetupUI.mobileprovision  ~/Library/MobileDevice/Provisioning\ Profiles/

      # 6) Rozpakowanie NDI_SDK.zip oraz libndi_ios_arm64.a.zip
      - name: Rozpakuj NDI_SDK.zip oraz libndi_ios_arm64.a.zip
        run: |
          set -e

          # Upewnij się, że katalog docs i libs istnieją
          mkdir -p libs

          # Rozpakuj NDI_SDK.zip -> libs/NDI_SDK/...
          if [ -f "libs/NDI_SDK.zip" ]; then
            unzip -q "libs/NDI_SDK.zip" -d libs/ || { echo "❌ Nie udało się rozpakować libs/NDI_SDK.zip"; exit 1; }
          else
            echo "❌ Brakuje pliku libs/NDI_SDK.zip"; exit 1
          fi

          # Rozpakuj libndi_ios_arm64.a.zip -> libs/libndi_ios_arm64.a
          if [ -f "libs/libndi_ios_arm64.a.zip" ]; then
            unzip -q "libs/libndi_ios_arm64.a.zip" -d libs/ || { echo "❌ Nie udało się rozpakować libs/libndi_ios_arm64.a.zip"; exit 1; }
          else
            echo "ℹ️ Plik libs/libndi_ios_arm64.a.zip nie istnieje, pomijam."
          fi

      # 7) Budowanie (Archive) z ręcznym podpisywaniem
      - name: Build Archive
        run: |
          set -o pipefail
          KEYCHAIN_PATH="$(security list-keychains -d user | tr -d '"' | tr '\n' ' ')"

          xcodebuild archive \
            -project "$APP_PROJECT" \
            -scheme "$APP_SCHEME" \
            -configuration Release \
            -archivePath "$APP_ARCHIVE_PATH" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            CODE_SIGN_KEYCHAIN="$KEYCHAIN_PATH" \
            'PROVISIONING_PROFILE_SPECIFIER=LayerMapper AppStore Profile' \
            'PROVISIONING_PROFILE_SPECIFIER[bundleId=com.layermapper.mobile.screenbroadcast]=ScreenBroadcast AppStore Profile' \
            'PROVISIONING_PROFILE_SPECIFIER[bundleId=com.layermapper.mobile.screenbroadcast.setup]=ScreenBroadcastSetupUI AppStore Profile'

      # 8) Eksport gotowego .ipa
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath "$APP_ARCHIVE_PATH" \
            -exportOptionsPlist <<EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <true/>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>${APP_BUNDLE_ID}</key>
                <string>LayerMapper AppStore Profile</string>
              </dict>
              <key>teamID</key>
              <string>${{ secrets.TEAM_ID }}</string>
            </dict>
            </plist>
            EOF \
            -exportPath "$HOME"

      # 9) Upload do App Store Connect
      - name: Upload to App Store (altool)
        env:
          APPLE_ID:               ${{ secrets.APPLE_ID }}
          APP_SPECIFIC_PASSWORD:  ${{ secrets.APP_SPECIFIC_PASSWORD }}
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file "$APP_IPA_PATH" \
            --username "$APPLE_ID" \
            --password "$APPLE_SPECIFIC_PASSWORD" \
            --output-format xml

      # 10) Sprzątanie: usunięcie utworzonego keychain
      - name: Cleanup build keychain
        if: always()
        run: |
          security delete-keychain build.keychain || true
          security delete-keychain build.keychain-db || true
