name: Build & Upload to App Store

on:
  push:
    branches: [ main ]
    tags:     [ 'v*.*.*' ]

jobs:
  build_and_submit:
    name: Build i wyślij do App Store Connect
    runs-on: macos-latest

    env:
      APP_SCHEME:  LayerMapper
      APP_PROJECT: LayerMapper.xcodeproj
      ARCHIVE:     $HOME/LayerMapper.xcarchive
      IPA_PATH:    $HOME/LayerMapper.ipa
      EXPORT_METHOD: app-store

    steps:
    # 1 ▸ Checkout repo (z Git LFS)
    - uses: actions/checkout@v4
      with:
        lfs: true

    # 2 ▸ Narzędzia (altool)
    - run: sudo gem install cocoapods --no-document

    # 3 ▸ Keychain + certyfikat Apple Distribution (.p12)
    - name: Create temp keychain
      run: |
        set -x
        security create-keychain -p "" build.keychain
        security set-keychain-settings -lut 21600 build.keychain
        security unlock-keychain -p "" build.keychain
        security list-keychains -d user | tr -d '"' | \
          xargs security list-keychains -s build.keychain
    - name: Import distribution certificate
      env:
        P12_BASE64:  ${{ secrets.P12_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      run: |
        set -x
        echo "$P12_BASE64" | base64 -d > cert.p12
        security import cert.p12 -k ~/Library/Keychains/build.keychain \
          -P "$P12_PASSWORD" -T /usr/bin/codesign

    # 4 ▸ Provisioning profiles → ~/Library/MobileDevice/Provisioning Profiles/
    - name: Decode & install provisioning profiles
      env:
        MOBILEPROVISION_BASE64:          ${{ secrets.MOBILEPROVISION_BASE64 }}
        MOBILEPROVISION_BROADCAST_BASE64: ${{ secrets.MOBILEPROVISION_BROADCAST_BASE64 }}
        MOBILEPROVISION_SETUP_BASE64:     ${{ secrets.MOBILEPROVISION_SETUP_BASE64 }}
      run: |
        set -x
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$MOBILEPROVISION_BASE64"          | base64 -d > LM.mobileprovision
        echo "$MOBILEPROVISION_BROADCAST_BASE64" | base64 -d > BC.mobileprovision
        echo "$MOBILEPROVISION_SETUP_BASE64"     | base64 -d > SU.mobileprovision
        cp *.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

    # 5 ▸ Debug – pokaż Name | UUID | AppID
    - name: Debug – list installed profiles
      run: |
        for p in ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision; do
          NAME=$(security cms -D -i "$p" | plutil -extract Name raw -)
          UUID=$(security cms -D -i "$p" | plutil -extract UUID raw -)
