name: Build & Upload to App Store

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-submit:
    name: Build i Wyslij do App Store
    runs-on: macos-latest

    env:
      APP_SCHEME: "LayerMapper"
      APP_WORKSPACE: ""                          # jeśli nie używasz workspace
      APP_PROJECT: "LayerMapper.xcodeproj"
      APP_EXPORT_METHOD: "app-store"
      APP_BUNDLE_ID: "com.layermapper.mobile"
      APP_ARCHIVE_PATH: "$HOME/Library/Developer/Xcode/Archives/$(date +%Y-%m-%d)/LayerMapper.xcarchive"
      APP_IPA_PATH: "$HOME/LayerMapper.ipa"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Ustaw Ruby (dla altool)
        run: |
          sudo gem install cocoapods --no-document

      # —— Stworzenie Keychain i import .p12 —— 
      - name: Create keychain
        run: |
          security create-keychain -p "" build.keychain
          security set-keychain-settings -lut 21600 build.keychain
          security unlock-keychain -p "" build.keychain
          security list-keychains -s "$(security list-keychains -d user | tr -d '"' | tr '\n' ' ')" build.keychain

      - name: Decode and install Distribution Certificate (.p12)
        run: |
          echo "$P12_BASE64" | base64 --decode > distribution.p12
          security import distribution.p12 -k ~/Library/Keychains/build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
        env:
          P12_BASE64: ${{ secrets.P12_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}

      # —— Decode i zainstalowanie wszystkich trzech provisioning profiles —— 
      - name: Decode and install Provisioning Profiles
        run: |
          echo "$MOBILEPROVISION_MAIN_BASE64"    | base64 --decode > LayerMapper.mobileprovision
          echo "$MOBILEPROVISION_BROADCAST_BASE64" | base64 --decode > ScreenBroadcast.mobileprovision
          echo "$MOBILEPROVISION_SETUP_BASE64"    | base64 --decode > ScreenBroadcastSetupUI.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp LayerMapper.mobileprovision    ~/Library/MobileDevice/Provisioning\ Profiles/
          cp ScreenBroadcast.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          cp ScreenBroadcastSetupUI.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        env:
          MOBILEPROVISION_MAIN_BASE64:    ${{ secrets.MOBILEPROVISION_MAIN_BASE64 }}
          MOBILEPROVISION_BROADCAST_BASE64: ${{ secrets.MOBILEPROVISION_BROADCAST_BASE64 }}
          MOBILEPROVISION_SETUP_BASE64:    ${{ secrets.MOBILEPROVISION_SETUP_BASE64 }}

      # —— Rozpakowanie bibliotek NDI —— 
      - name: Unzip NDI SDK for iOS
        run: |
          mkdir -p "LayerMapper/LayerMapper/NDI SDK for Apple"
          unzip -q ndi_sdk_for_ios.zip -d "LayerMapper/LayerMapper/NDI SDK for Apple"

      - name: Unzip libndi_ios.a
        run: |
          mkdir -p "LayerMapper/ScreenBroadcast"
          unzip -q libndi_ios.zip -d "LayerMapper/ScreenBroadcast"

      # —— Budowanie (Archive) – z ręcznym podaniem provisioning profile dla trzech bundle IDs —— 
      - name: Build Archive
        run: |
          set -o pipefail
          KEYCHAIN_PATH="$(security list-keychains -d user | tr -d '"' | tr '\n' ' ')"

          xcodebuild archive \
            -project "$APP_PROJECT" \
            -scheme "$APP_SCHEME" \
            -configuration Release \
            -archivePath "$APP_ARCHIVE_PATH" \
            CODE_SIGN_KEYCHAIN="$KEYCHAIN_PATH" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="LayerMapper AppStore Profile" \
            PROVISIONING_PROFILE_SPECIFIER[bundleId="com.layermapper.mobile.screenbroadcast"]="ScreenBroadcast AppStore Profile" \
            PROVISIONING_PROFILE_SPECIFIER[bundleId="com.layermapper.mobile.screenbroadcast.setup"]="ScreenBroadcastSetupUI AppStore Profile"

      # —— Eksport .ipa —— 
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath "$APP_ARCHIVE_PATH" \
            -exportOptionsPlist <<EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <true/>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>${APP_BUNDLE_ID}</key>
                <string>LayerMapper AppStore Profile</string>
              </dict>
              <key>teamID</key>
              <string>${{ secrets.TEAM_ID }}</string>
            </dict>
            </plist>
            EOF \
            -exportPath "$HOME"

      # —— Upload do App Store —— 
      - name: Upload to App Store (altool)
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file "$APP_IPA_PATH" \
            --username "${{ secrets.APPLE_ID }}" \
            --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
            --output-format xml
        env:
          APPLE_ID:                 ${{ secrets.APPLE_ID }}
          APPLE_SPECIFIC_PASSWORD:  ${{ secrets.APPLE_SPECIFIC_PASSWORD }}

      # —— Sprzątanie keychain ——
      - name: Cleanup build keychain
        if: always()
        run: |
          security delete-keychain build.keychain
