name: Build & Upload to App Store

on:
  push:
    branches: [ main ]
    tags:    [ 'v*.*.*' ]

jobs:
  build_and_submit:
    name: Build i wyślij do App Store Connect
    runs-on: macos-14        # Xcode 16 + iOS 18 SDK

    env:
      APP_SCHEME:    LayerMapper
      APP_PROJECT:   LayerMapper.xcodeproj
      ARCHIVE_DIR:   $HOME/Library/Developer/Xcode/Archives
      EXPORT_METHOD: app-store

    steps:
    # 1. Checkout
    - uses: actions/checkout@v4
      with:
        lfs: true

    # 2. Xcode 16
    - name: Select Xcode 16
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16'

    # 3. CocoaPods (dla altool)
    - run: sudo gem install cocoapods --no-document
      name: Install CocoaPods

    # 4-5. Keychain + certyfikat (bez zmian)
    - name: Create temporary keychain
      run: |
        set -x
        security create-keychain -p "" build.keychain
        security set-keychain-settings -lut 21600 build.keychain
        security unlock-keychain -p "" build.keychain
        security list-keychains -d user | tr -d '"' | xargs security list-keychains -s build.keychain

    - name: Import distribution certificate
      env:
        P12_BASE64:   ${{ secrets.P12_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      run: |
        set -x
        echo "$P12_BASE64" | base64 --decode > dist.p12
        security import dist.p12 \
          -k ~/Library/Keychains/build.keychain \
          -P "$P12_PASSWORD" \
          -T /usr/bin/codesign \
          -T /usr/bin/xcodebuild \
          -T /usr/bin/security
        security set-key-partition-list -S apple-tool:,codesign:,apple: -s -k "" build.keychain

    # 6-7. Provisioning profiles (jak wcześniej)
    - name: Decode & install provisioning profiles
      env:
        MOBILEPROVISION_BASE64:           ${{ secrets.MOBILEPROVISION_BASE64 }}
        MOBILEPROVISION_BROADCAST_BASE64: ${{ secrets.MOBILEPROVISION_BROADCAST_BASE64 }}
        MOBILEPROVISION_SETUP_BASE64:     ${{ secrets.MOBILEPROVISION_SETUP_BASE64 }}
      run: |
        set -x
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$MOBILEPROVISION_BASE64"           | base64 --decode > LM.mobileprovision
        echo "$MOBILEPROVISION_BROADCAST_BASE64" | base64 --decode > BC.mobileprovision
        echo "$MOBILEPROVISION_SETUP_BASE64"     | base64 --decode > SETUP.mobileprovision
        cp *.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

    - id: uuids
      run: |
        echo "app_uuid=$(security cms -D -i LM.mobileprovision    | plutil -extract UUID raw -)"     >> $GITHUB_OUTPUT
        echo "bc_uuid=$(security cms -D -i BC.mobileprovision     | plutil -extract UUID raw -)"     >> $GITHUB_OUTPUT
        echo "setup_uuid=$(security cms -D -i SETUP.mobileprovision | plutil -extract UUID raw -)"   >> $GITHUB_OUTPUT

    # 8. Artefakty NDI
    - name: Unzip NDI artefacts
      run: |
        set -x
        mkdir -p libs
        unzip -q libs/NDI_SDK.zip            -d libs/
        unzip -q libs/libndi_ios_arm64.a.zip -d libs/

    # 9. Budujemy archiwum ➜ outputs: archive_bundle
    - name: Build Xcode archive
      id: build
      env:
        APP_UUID:   ${{ steps.uuids.outputs.app_uuid }}
        BC_UUID:    ${{ steps.uuids.outputs.bc_uuid }}
        SETUP_UUID: ${{ steps.uuids.outputs.setup_uuid }}
      run: |
        set -euo pipefail
        DATE_DIR=$(date +%Y-%m-%d)
        mkdir -p "$ARCHIVE_DIR/$DATE_DIR"
        ARCHIVE_BASE="$ARCHIVE_DIR/$DATE_DIR/LayerMapper"
        xcodebuild archive \
          -project "$APP_PROJECT" \
          -scheme  "$APP_SCHEME" \
          -configuration Release \
          -archivePath "$ARCHIVE_BASE" \  # <-- bez .xcarchive!
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="Apple Distribution" \
          CODE_SIGN_KEYCHAIN="$HOME/Library/Keychains/build.keychain" \
          "PROVISIONING_PROFILE[com.layermapper.mobile]=$APP_UUID" \
          "PROVISIONING_PROFILE[com.layermapper.mobile.screenbroadcast]=$BC_UUID" \
          "PROVISIONING_PROFILE[com.layermapper.mobile.screenbroadcast.setup]=$SETUP_UUID"

        ARCHIVE_BUNDLE="${ARCHIVE_BASE}.xcarchive"
        echo "::notice::Archive created at $ARCHIVE_BUNDLE"
        # zapisujemy pełną ścieżkę do outputs
        echo "archive_bundle=$ARCHIVE_BUNDLE" >> $GITHUB_OUTPUT

    # 10. Szybka kontrola – czy archiwum istnieje
    - name: Verify archive path
      run: |
        ls -l "${{ steps.build.outputs.archive_bundle }}"

    # 11. Eksport ipa
    - name: Export .ipa
      env:
        APP_UUID:   ${{ steps.uuids.outputs.app_uuid }}
        BC_UUID:    ${{ steps.uuids.outputs.bc_uuid }}
        SETUP_UUID: ${{ steps.uuids.outputs.setup_uuid }}
      run: |
        set -euo pipefail
        ARCHIVE_PATH="${{ steps.build.outputs.archive_bundle }}"

        cat > exportOptions.plist <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
          <dict>
            <key>method</key>            <string>${EXPORT_METHOD}</string>
            <key>teamID</key>            <string>${{ secrets.TEAM_ID }}</string>
            <key>signingStyle</key>      <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.layermapper.mobile</key>                   <string>${APP_UUID}</string>
              <key>com.layermapper.mobile.screenbroadcast</key>   <string>${BC_UUID}</string>
              <key>com.layermapper.mobile.screenbroadcast.setup</key><string>${SETUP_UUID}</string>
            </dict>
          </dict>
        </plist>
        EOF

        xcodebuild -exportArchive \
          -archivePath "$ARCHIVE_PATH" \
          -exportOptionsPlist exportOptions.plist \
          -exportPath "$HOME"

    # 12. Upload do App Store Connect
    - name: Upload to App Store Connect
      env:
        APPLE_ID:              ${{ secrets.APPLE_ID }}
        APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
      run: |
        set -x
        xcrun altool --upload-app \
          --file "$HOME/LayerMapper.ipa" \
          --type ios \
          --username "$APPLE_ID" \
          --password "@env:APP_SPECIFIC_PASSWORD" \
          --output-format xml

    # 13. Cleanup keychain
    - if: always()
      name: Cleanup keychain
      run: security delete-keychain build.keychain || true
